### ISSUE TITLE
Conda does not activate in submitted processes

### ISSUE THREAD

**Issue by esteinig** [dsarov/ARDaP#10]
Nextflow submission in `.command.run` tries to activate conda environments using `source activate` but this is not supported in latest conda versions, where this is replaced with `conda activate`. It is an open issue at https://github.com/nextflow-io/nextflow/issues/1195

Thinking about a fix we can implement until it is resolved.

**Comment by esteinig** [comment]
So, it does not work when `conda` is using the latest (> `v.4.4.0`) initiation block that can be added to `~/.bashrc` after installation of `conda`.

However it does work when the initiation block is missing and `conda` is simply in `$PATH`. Not sure how to best harmonize that for users?

**Comment by dsarov** [comment]
I think a nextflow update has mostly fixed this bug. I haven't encountered it for ages.
