### ISSUE TITLE
Something wrong with Trimmomatic

### ISSUE THREAD

**Issue by vlgShpak** [dsarov/ARDaP#12]
Hello! I have installed ARDaP on my desktop. Unfortunately I always catch some kind of Trimmomatic error. I have attached the output to this message. 
[log.txt](https://github.com/dsarov/ARDaP/files/3839470/log.txt)

**Comment by dsarov** [comment]
Hi vlgShpak,

I think it is just to do with the way you are calling the software. Try renaming your reads to end with the suffix _1.fastq.gz and _2.fastq.gz and see how you go with the default parameters.

You can probably change the --fastq flag as well to --fastq "*_{001,002}.fastq.gz"
