### ISSUE TITLE
SQL queries in Nextflow

### ISSUE THREAD

**Issue by esteinig** [dsarov/ARDaP#3]
Michael made me aware of the great use of issues to collaborate, so just gonna pin down a couple of things to remind myself and get this done :)

First sourcing the SQL query scripts... I actually like it this way, it's really clean. The easiest option would be to copy the scripts right into the into the workflow processes, but it'd get a bit messy in the main script.

**Comment by dsarov** [comment]
Yeah, it actually works really well. Realised how terribly written my SQL query script was written when I had to pull it apart.

**Comment by esteinig** [comment]
Ha, always happens. I probably rewrite functions 3 - 4 times until I am satisfied and moved on from the idea to a working example and maybe even good code :)

Looking good with the scripts, so will close this issue.
