### ISSUE TITLE
Unable install ARDaP

### ISSUE THREAD

**Issue by Dx-wmc** [dsarov/ARDaP#35]
Hi, I recently read your paper published in Genome Medicine and want to install this nice software. However,  there was a problem with the default installation method and I was unable to install using conda. I presume that the yaml file you provided is not complete enough. Would you be able to provide a yaml file that contains the one you are using? `conda env export -n ardap > ardap.yaml `would be helpful!

**Comment by dsarov** [comment]
[new.ardap.zip](https://github.com/user-attachments/files/15829007/new.ardap.zip)
Hi Dave,

I've output the full environment to the attached file. Could you let me know if that works? Happy to update the yaml if that fixes the issue.

Cheers,

Derek

**Comment by dsarov** [comment]
Oh, I think I see what the problem is. I'm using an older version of nextflow that now has compatibility issues with java. I'll need to update to the latest nextflow. I'll do that and let you know.

**Comment by Dx-wmc** [comment]
Hi Derek, I have tried the YAML file you provided, and it seems to work. However, upon checking the generated results, they appear to be incorrect. Is it possible for you to provide an example FASTQ file and the corresponding expected results? This would allow me to evaluate whether the installation is correct.

In addition, the warning message I prompted seems to have a problem with the nextflow you mentioned. 
`WARN: Input tuple does not match input set cardinality declared by process `Trimmomatic` -- offending value: [1011_1, home/data/usr/dx/software/ardap/assemblies/1011_1.fq.gz]`

**Comment by dsarov** [comment]
Hi David,
Apologies for the slow reply. Could you send me the command you used to run ardap and the list of files you are trying to run it across? I've been having separate issues with gatk versions but the error above seems related to file naming.
Thanks,

**Comment by Dx-wmc** [comment]
Hi Derek, the command I used is: `nextflow run main.nf --species Pseudomonas_aeruginosa --fastq assemblies/*_{1,2}.fq.gz`. The files I used are: `ls assemblies/
1011_1.fq.gz   1011_2.fq.gz`

**Comment by dsarov** [comment]
Hi David,

Could you try moving the raw reads to the base directory and re-running with the command below? I think the fastq flag needs to be  ``` "*_{1,2}.fq.gz"``` not  ```*_{1,2}.fq.gz```
Cheers,

Derek

```nextflow run main.nf --species Pseudomonas_aeruginosa --fastq "*_{1,2}.fq.gz"```

**Comment by Dx-wmc** [comment]
Hi Derek, I have tried the command you provided and have moved the raw reads to the base directory. However, it occurred in error. 

The error message: 
```
executor >  local (6)
executor >  local (6)
[-        ] process > IndexReference     -
[0c/0dcf7f] process > Trimmomatic (1011) [100%] 5 of 5, failed: 5, retries: 4 ✘
[-        ] process > Downsample         -
[-        ] process > ReferenceAlignment -
[-        ] process > Deduplicate        -
[-        ] process > VariantCalling     -
[-        ] process > SqlSnpsIndels      -
[-        ] process > R_report           -
[bb/9db178] NOTE: Process `Trimmomatic (1011)` terminated with an error exit status (1) -- Execution is retried (1)
[93/9a83c1] NOTE: Process `Trimmomatic (1011)` terminated with an error exit status (1) -- Execution is retried (2)
[24/05ef3e] NOTE: Process `Trimmomatic (1011)` terminated with an error exit status (1) -- Execution is retried (3)
[d0/2ba750] NOTE: Process `Trimmomatic (1011)` terminated with an error exit status (1) -- Execution is retried (4)
WARN: Killing pending tasks (1)
Error executing process > 'Trimmomatic (1011)'

Caused by:
  Process `Trimmomatic (1011)` terminated with an error exit status (1)

Command executed:

  mv 1011_1.fq.gz 1011_1.fq.gz
  mv 1011_2.fq.gz 1011_2.fq.gz

Command exit status:
  1

Command output:
  (empty)

Command error:
  mv: '1011_1.fq.gz' and '1011_1.fq.gz' are the same file

Work dir:
  /home/data/usr/dx/software/ardap/work/0c/0dcf7f22e18e882b79f8e804bb614a

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by dsarov** [comment]
Hi David,

Thanks for sending through! I can see that bug and will fix it shortly. You should be able to get around the problem by renaming your reads to ```1011_1.fastq.gz``` and ```1011_2.fastq.gz``` and starting the software with ```nextflow run main.nf --species Pseudomonas_aeruginosa --fastq "*_{1,2}.fastq.gz"```

**Comment by Dx-wmc** [comment]
Hi Derek, I am pleased to inform you that the method you provided works. And I checked the results, and it seemed right. However, I would suggest that the Readme file be improved to avoid problems like mine from recurring.

**Comment by dsarov** [comment]
Thanks David! Will do.
