### ISSUE TITLE
Cleanup directory structure

### ISSUE THREAD

**Issue by esteinig** [dsarov/ARDaP#4]
For eventual release, I am going to clean up the directory structure, so we have some dedicated subdirectories for resources and can remove the old scripts.

**Comment by dsarov** [comment]
Bit cleaner now. Will fix up the remainder when we have the pipeline closer to running in nextflow

**Comment by esteinig** [comment]
Oh, I was gonna check this, thanks for this :) More a reminder for release as you point out.

**Comment by esteinig** [comment]
Just cleaned up all the dependency remnants covered by the Conda environment or Dockerfile in commit 1d502e9fe808465759b6c0b8a579b6c233aa990a
