### ISSUE TITLE
Drop _sequence input glob

### ISSUE THREAD

**Issue by esteinig** [dsarov/ARDaP#6]
Can we drop the `_sequence_` substring requirement from the default configuration for the Fastq input in the Nextflow implementation? I think the most common ones are simple `.fq.gz` and `.fastq.gz`. It'd be more of a hurdle for users to rename their files or to specify a different glob pattern on the command line.

**Comment by dsarov** [comment]
Will do. It's just how the raw data is setup on my drives (and a hangover from SPANDx)

**Comment by esteinig** [comment]
Hey Derek, thanks for this - you can always specify the `sequence` pattern on the command line with `--fastq '*_{1,2}_sequence.fq.gz'` so you don't have to adjust your old collections. Just thought this would be more convenient for other users :)

Removed `_sequence` from config in commit 1951a74ee38b73cecd98820eeba4e1e7d59c02e7.
