### ISSUE TITLE
Losing processing of multiple samples following downsampling process

### ISSUE THREAD

**Issue by dsarov** [dsarov/ARDaP#7]
Hey Eike,
I'm doing something incredibly stupid and can't get multiple samples to run through the pipeline. They go okay during the downsampling process but when it comes to the alignment process the second read pair gets killed and I'm down to just a single sample. I think I'm not setting an input or output channel correctly and something is silently killing of my second sample. Let me know if that doesn't make sense!

**Comment by esteinig** [comment]
I'll debug this afternoon. There are some quirks that can cause this. If you want try something in the meantime, my haphazard guess is that you are piping output into multiple channels? if so, try putting them in brackets like:

`set id, file('outfile.txt') into (channel1, channel2)`

**Comment by esteinig** [comment]
I just looked at the code for `Downsample` and it looks fine. I think this quirk can occur when you are missing brackets in any process, so will check through later.

**Comment by dsarov** [comment]
Thanks Eike. I thought it might be this line 

set id, file("${id}_1_cov.fq.gz"), file("${id}_2_cov.fq.gz") into (alignment, alignmentCARD)

but agree it looks okay. I wasn't really looking outside this spot so could definitely be errors elsewhere

**Comment by dsarov** [comment]
Think the ReferenceAlignment process is consuming the bwa_index file from the bwa_alignment channel and not running across more than the first sample?

**Comment by dsarov** [comment]
I've pushed a workaround to the v1.5 branch. I included the reference indices in the database directory of the ARDaP distro and just included the path to those files in the start of ardap.nf. 

I think it has something to do with the input line in the reference alignment section making that process loop once only rather than looping across all the input data.

Terrible workaround though and I'm not sure if I'll hit that problem again later

**Comment by esteinig** [comment]
Does it stage the reference file in the working directory for `ReferenceAlignment`?

I have come across this before and this was my solution as well. It's somethign with specifying multiple inputs and how the process is then combined into let's say input `line1` x `line2` shell script combinations and executed. 

However something interferes with this when input `line1` is one value or file like specified here. 

My suggestion is leave it hardcoded in the meantime like you did since the validation of `ARDaP` is also dependent on the reference sequence used (for now). I want to check this out closer and see how to get around it, since it's been bugging me for a while.

**Comment by dsarov** [comment]
Lines 93 and 176

It stages them once and then doesn't stage them a second time. 

Good to hear you've seen the same prob before and I can see it happening later in the script too after I started testing this fix

**Comment by dsarov** [comment]
Happens again in referenceCoverage but I haven't taken a look at that one either. Probably the same type of error

**Comment by esteinig** [comment]
Something is off then. I think it's some channel error tat's not caught properly because these channels used to work in the prototype.

**Comment by esteinig** [comment]
I'm gonna have a look in a bit, maybe don't change too much for now

**Comment by dsarov** [comment]
For sure. I won't touch it for the while. I'm in the lab all arvo too

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by esteinig** [comment]
Me too, just doing a coral mock community run for our AI paper on an old flowcell. One year old and still pretty much as good as new!

**Comment by dsarov** [comment]
Finally figured it out. Still not precisely sure what was going wrong but I'm much more familiar with nextflow documentation now...
