### ISSUE TITLE
Potential dependency issue with the ape package in R

### ISSUE THREAD

**Issue by dsarov** [dsarov/ARDaP#8]
Not completely convinced this error will occur outside my HPC but after an automated conda install the R package "ape" didn't function due to missing dependencies. Manually installing ape fixed the issue.

**Comment by esteinig** [comment]
Hmmm interesting I'll have a look at the recipe in the Anaconda repository. Might be worth checking if there is another R channel that has a different version. Maybe `conda-forge`?

**Comment by dsarov** [comment]
Fixed now. I've removed the R requirement in preference to generation of html reports.
